apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: importador-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/eurival/importador.git' # Substitua pelo seu repo
    targetRevision: main
    path: infra/kubernetes # A pasta onde os manifestos acima est√£o
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gedtotal-apps 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true