apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - importador-config.yaml
  - importador-deployment.yaml
  - service.yaml
  - hpa.yaml
  - servicemonitor.yaml
images:
  - name: docker.io/eurival/importador
    newName: docker.io/eurival/importador
    newTag: 1.0.2
