apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - importador-config.yaml  
  - importador-deployment.yaml
  - importador-service.yaml
  - hpa.yaml (se tiver)
  - servicemonitor.yaml (se tiver)

images:
  - name: docker.io/eurival/importador 
    newName: docker.io/eurival/importador  
    newTag: "0.0.1-SNAPSHOT" 