apiVersion: v1
kind: Service
metadata:
  name: importador-service
  namespace: gedtotal-apps
  labels:
    app: importador-service # <--- O ServiceMonitor busca por ISSO aqui
spec:
  type: ClusterIP
  selector:
    app: importador # <--- O Service busca os Pods por ISSO aqui
  ports:
    - name: http
      port: 8080
      targetPort: 8080